### ISSUE TITLE
Cleanup the .gitignore file

### ISSUE THREAD

**Issue by leandor** [wrye-bash/CBash#10]
It seems to have been auto-generated at some point.

I'll remove everything not related to this repositories' content and re-add by hand the patterns needed as they come up.

**Comment by leandor** [comment]
I wonder... should issues be closed when they are done? Or when they are merged to _the_ 'trunk' whatever branch that is? (here would be 'dev')

**Comment by Utumno** [comment]
Usually when added to dev yes but up to you for this repo. If you edit the issue message to read Closes #xx or fixes#xx github will autoclose the issue - syntax https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by leandor** [comment]
Perfect, thanks. I'll hold on for a bit more on merging to dev. 

I hope I can finish the "RecordProcessor" warning first. 

Once I have that solved, I'm gonna try to setup a automatic release on appveyor from dev (tagged as unstable) and then after that I'll do the merge.

**Comment by Infernio** [comment]
Closed in d4c16e2fbb68f52551eb0ce070213ccef12bed6a.
