### ISSUE TITLE
Compilation speedup needed

### ISSUE THREAD

**Issue by leandor** [wrye-bash/CBash#12]
Currently fully compiling CBash from sources on Windows takes ~15 mins (see -> https://ci.appveyor.com/project/leandor/cbash/history) which makes development a bit annoying. 

It's hard to try anything that affect the build setup created by CMake without triggering a full recompilation afterwards.

That's why I'm about to start trying some options to see if I can speed up compilation a bit.

First thing I'm gonna try is to setup CMake to use pre compiled headers for Visuall Studio, by using one of these (_cough_hacks_cough_) solutions:
- https://github.com/larsch/cmake-precompiled-header
- http://stackoverflow.com/questions/148570/using-pre-compiled-headers-with-cmake
- https://github.com/sakra/cotire

Second thing, even if the above works, I intend to split up CBash project in a couple of static lib projects + one static lib project per game to hold all the records and modfile.

**Comment by Infernio** [comment]
Note: `cotire` was added in c57940f4ba662b98c7efae37c717615b48348d6f.

**Comment by Infernio** [comment]
Compilation is pretty fast now, putting on backburner in case it gets worse again.
