### ISSUE TITLE
Finish AppVeyor configuration

### ISSUE THREAD

**Issue by leandor** [wrye-bash/CBash#14]
AppVeyor is already setup to monitor this repository's commits. 

---

TODO
- [ ] Finalize configuration by added test execution and package artifacts to upload as a github release
- [ ] Make sure that after everything is setup correctly, only execute builds on dev and master branch (not sure on this yet)
- [ ] Document details of utilizing AppVeyor (and eventually travis-ci) for future members of the project
- [ ] Check how to make AppVeyor (and eventually travis-ci) dashboard and configuration editable by team members.

**Comment by leandor** [comment]
Updated description with a task list of items I need to check to consider this complete.

**Comment by Infernio** [comment]
Putting all CI-related issues on backburner for now. Maybe revisit once Wrye Bash mainline gets close to CI?
