### ISSUE TITLE
64bit Port

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/CBash#23]
CBash is one of two reasons WB is stuck on 32bit (the other is https://github.com/wrye-bash/wrye-bash/issues/431), denying the entire program (but especially PBash) a ~30% speedup. We are pretty close - most methods seem to work - but a lovely traceback stands in our way:

```
Traceback (most recent call last):
  File "bash\balt.py", line 2500, in __Execute
    self.Execute()
  File "bash\balt.py", line 1604, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\mod_links.py", line 932, in Execute
    if not self._Execute(): return # prevent settings save
  File "bash\basher\mod_links.py", line 976, in _Execute
    doCBash=self.doCBash)
  File "bash\bosh\__init__.py", line 2025, in rescanMergeable
    return self._rescanMergeable(names, prog, doCBash, return_results)
  File "bash\bosh\__init__.py", line 2054, in _rescanMergeable
    canMerge = is_mergeable(fileInfo, self, reasons)
  File "bash\bosh\_mergeability.py", line 224, in isCBashMergeable
    if not _modIsMergeableLoad(modInfo, minfos, reasons) and not verbose:
  File "bash\bosh\_mergeability.py", line 212, in _modIsMergeableLoad
    reasons.append(_(u'Is a master of non-mergeable mod(s): %s.') % u', '.join(sorted(dependent)))
  File "bash\cint.py", line 15301, in __exit__
    self.Close()
  File "bash\cint.py", line 15317, in Close
    _CDeleteCollection(self._CollectionID)
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

Firing up Visual Studio and breakpointing `cb_DeleteCollection` shows that the access violation actually occurs in the `Collection` destructor:
https://github.com/wrye-bash/CBash/blob/e7b99dc6339345acc782730bc658d2291472d5c6/src/Collection.cpp#L163-L171
Specifically, `delete ModFiles[p];` crashes.

Breakpointing inside the destructor shows this:

![destructor](https://user-images.githubusercontent.com/2845240/65341745-54458200-dbd1-11e9-911e-7305926900e7.png)

The first two `ModFile` instances (`Oblivion.esm` and `Unofficial Oblivion Patch.esp`, if you're curious) delete correctly, but the third one (`Oblivion Citadel Door Fix.esp.ghost`) crashes. As you can see from the screenshot, there's definitely something off about the third `ModFile` - it seems to be missing everything from `TES4File`.

**Comment by Infernio** [comment]
Turns out that this is probably all Python-side. From `cint.py`:
```python
    def load(self):
        def _callback(current, last, modName):
            return True

        cb = CFUNCTYPE(c_bool, c_uint32, c_uint32, c_char_p)(_callback)
        _CLoadCollection(self._CollectionID, cb)

        _NumModsIDs = _CGetLoadOrderNumMods(self._CollectionID)
        if _NumModsIDs > 0:
            cModIDs = (c_ulong * _NumModsIDs)()
            _CGetLoadOrderModIDs(self._CollectionID, byref(cModIDs))
            self.LoadOrderMods = [self._ModType(ModID) for ModID in cModIDs]

        _NumModsIDs = _CGetAllNumMods(self._CollectionID)
        if _NumModsIDs > 0:
            cModIDs = (c_ulong * _NumModsIDs)()
            _CGetAllModIDs(self._CollectionID, byref(cModIDs))
            self.AllMods = [self._ModType(ModID) for ModID in cModIDs]
```

Note those `(c_ulong * _NumModsIDs)()` calls, they make new arrays with `_NumModsIDs()` elements. What are the array elements? `c_ulong`s, of course. Those then get filled with pointers to the mod file objects inside CBash.
This all works fine on x86, where the size of a pointer == the size of a c_ulong.
But on x64 Windows:
```cpp
assert(sizeof(unsigned long) == 4) // passes
```

Which means we were stuffing 64bit pointers into arrays of 32bit integers. That can't end well, and was leading to the crash. Replacing the calls above with `(c_uint64 * _NumModsIDs())` (or even better, defining an alias `c_pointer = c_uint64` and using that) makes the patch dialog appear again. There are definitely still other parts of `cint` that have this same problem - the patch crashes shortly after clicking `Build Patch`.

**Comment by Utumno** [comment]
Thanks for looking into this! Would be great to get rid of the 32 compatibility for 307 - a pity that there are 959 matches for 32 in cint :P

**Comment by Utumno** [comment]
To begin with -  anyway cint has FNV classes - would make sense to rip them into another module and concentrate on the Oblivion side? Would go in line with our load-game-specific stuff line in  wrye-bash/wrye-bash#358 - see issue #2 here

**Comment by Infernio** [comment]
Yeah, I'll get stated on a branch for https://github.com/wrye-bash/wrye-bash/issues/264, seems like the only way to keep my sanity while fixing this 😛 
Should I keep the package named `cint` or take that opportunity to rename it to something better?

**Comment by Infernio** [comment]
Also, is it important to keep the whole `#See if cint is being used by Wrye Bash` code that allows `cint` to work even outside WB?

**Comment by Utumno** [comment]
> Should I keep the package named cint or take that opportunity to rename it to something better?

Keep it I'd say - too many references around, let's see how the refactoring goes, plus you know, now after all these years that I have people here actually _doing_ something, and long standing issues (like wx3 etc) are on their way we may concentrate on 308 on the patcher. Meaning we may rewrite it with cython or whatever and bin cbash altogether.

> Also, is it important to keep the whole #See if cint is being used by Wrye Bash code that allows cint to work even outside WB?

bin it for god's sake :P

**Comment by dh-nunes** [comment]
Trying out the 64bit branch - the popup asking whether we're sure we want to use CBash never appears and patch dialog never comes up. Culprit is [this `indirect`](https://github.com/wrye-bash/wrye-bash/blob/3e6a875f9f70b0e9bb5f780437c10b57c6f9de92/Mopy/bash/windows.py#L449) C function (why are using this instead of wxPython?) that never creates/shows the popup.

**Comment by dh-nunes** [comment]
All patchers are now running and the above issue with TaskDialogIndirect is now fixed (courtesy of lojack) in [ganda-64bit](https://github.com/wrye-bash/wrye-bash/tree/ganda-64bit) and in [ganda-wip](https://github.com/wrye-bash/CBash/compare/ganda-wip). I couldn't find other problems with 64bit
